### ISSUE TITLE
Messenger::create

### ISSUE THREAD

**Issue by mfiyalka** [tgallice/fb-messenger-sdk#12]
<?php
require_once __DIR__.'/../vendor/autoload.php';
use Tgallice\FBMessenger\Messenger;
$token = '***';
$messenger = Messenger::create($token);
$response = $messenger->sendMessage('865714890196550', 'My Message');

Error:
Fatal error: Uncaught Error: Call to undefined method Tgallice\FBMessenger\Messenger::create() in

**Comment by tgallice** [comment]
I think you use the current stable branch `0.1.0`. To have the last update, you need to use the  `dev-master` branch, which is not stable yet. I will release a new version soon. To install the dev version:
```
composer require tgallice/fb-messenger-sdk:1.0.x-dev
```

**Comment by mfiyalka** [comment]
It works, thank you.
