### ISSUE TITLE
Message and verify token

### ISSUE THREAD

**Issue by aram-eghiazaryan** [tgallice/fb-messenger-sdk#17]
How can I find message and verify token variables

**Comment by tgallice** [comment]
Can you explain a bit more what is the issue ?

**Comment by aram-eghiazaryan** [comment]
From where i can find received message variable to make case:break; code
like this?

2016-11-04 14:02 GMT+04:00 Thomas Gallice <notifications@github.com>:

**Comment by tgallice** [comment]
@aram-eghiazaryan I have make a bot example. Please have a look here: https://github.com/tgallice/fb-bot-example
