### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by tapos12** [tgallice/fb-messenger-sdk#2]
[InvalidArgumentException]                                                                                         
  Could not find package tgallice/fb-messenger-sdk at any version for your minimum-stability (stable). Check the pa  
  ckage spelling or your minimum-stability                                                                           
                                           

Could you please also improve the doc file?

**Comment by tgallice** [comment]
Actually, this package is not stable yet. If you want to use it, you need to define the `minimum-stability` as `dev` in your `composer.json` before require it.

For the documention, yes it need to be improved and it will be. Have you a question in mind ?

**Comment by tapos12** [comment]
well i have installed in a project somehow but how to proceed next , a bit of tut maybe could be helpful.

Thanks
