### ISSUE TITLE
CallbackEvent dispatcher

### ISSUE THREAD

**Issue by tgallice** [tgallice/fb-messenger-sdk#23]
This issue is related to the discution with @kormid about to dispatch callback events.

Here is my implementation throught:

Use the `symfony/event-dispatcher` package to avoid building a custom event-dispatcher
Here is the doc about it : https://symfony.com/doc/current/components/event_dispatcher.html

Make `CallbackEvent` extends `Symfony\Component\EventDispatcher\Event`
```php
use Symfony\Component\EventDispatcher\Event;

abstract class CallbackEvent extends Event
{
...
}
```

Add a dispatcher in `WebhookRequestHandler`
```php

    /**
     * @var EventDispatcherInterface
     */
    private $dispatcher;

    public function __construct($secret, $verifyToken, ServerRequestInterface $request = null, EventDispatcherInterface $dispatcher = null)
    {
        ...
        $this->dispatcher = $dispatcher ?! new EventDispatcher();
    }

    public function dispatchCallbackEvents()
    {
        foreach ($this->getAllCallbackEvents() as $event) {
            // Dispatch callback event based on the CallbackEvent::NAME
            $this->dispatcher->dispatch($event->getName(), $event);

            if ($event instanceof PostbackEvent) {
                // Dispatch postback payload event
                $this->dispatcher->dispatch($event->getPostback(), $event);
            }

            if ($event instanceof Message && $event->hasQuickReply()) {
                // Dispatch quick reply payload event
                $this->dispatcher->dispatch($event->getQuickReplyPayload(), $event);
            }
        }
    }

    /**
     * @param EventSubscriberInterface $subscriber
     */
    public function addEventSubscriber(EventSubscriberInterface $subscriber)
    {
        $this->dispatcher->addSubscriber($subscriber);
    }
```

This need to edit #19 to rename `CallbackEvent::TYPE` and `CallbackEvent::getType()` to  `CallbackEvent::NAME` and `CallbackEvent::getName()` 

**How to use it**

```php

// Create subscriber 
class myCustomSubscriber implements EventSubscriberInterface {
    public static function getSubscribedEvents()
    {
         return [
             MessageEvent::NAME => 'myCustomFunction',
         ];
    }
    public function myCustomFunction(MessageEvent $event)
    {
      ....
    }
}

$myCustomSubscriber = new myCustomSubscriber();

$webhookRequestHandler = new WebhookRequestHandler(...);
$webhookRequestHandler->addEventSubscriber($myCustomSubscriber);

if ($webhookRequestHandler->isValid()) {
    $webhookRequestHandler->dispatchCallbackEvents();
}
```

@kormid what do you think about it ? It's the almost the same than yours but which a more general purpose.

**Comment by kormid** [comment]
Working on it :)

**Comment by tgallice** [comment]
Nice ! Feel free to adapte :). I will rename and merge the PR #19 to rename TYPE to NAME.

**Comment by kormid** [comment]
I deleted my fork and created it again from scratch, was to complicated to do something else. I have programmed for some years, but this github, laravel, synfony thinks are just new for me xD

**Comment by tgallice** [comment]
No worries :) You will see git his very powerful and useful. Here a small summary I have made for you with the basic git command and use. https://gist.github.com/tgallice/a9d74c32aed956eaa6c882977e55483e

I recommand you to take a look a the complet documentation here : https://git-scm.com/doc

**Comment by tgallice** [comment]
And to use composer (which is a package manager for php) :

**Comment by kormid** [comment]
Composer can i manage haha ^^

**Comment by tgallice** [comment]
nice :)
