### ISSUE TITLE
Typing indicator is missing

### ISSUE THREAD

**Issue by Shaked** [tgallice/fb-messenger-sdk#40]
Hey, 

I hope I am just missing something, but it seems that it is impossible to send a [typing indicator](https://developers.facebook.com/docs/messenger-platform/send-api-reference/sender-actions)  without having a Message object. 

The whole idea of the typing indicator is to show the user that something is happening while the message is being generated. This feature might be valuable *before* a message is going to be sent, e.g when the backend of the bot is doing some processing but wants to show the user that something is happening and they should wait.

What do you think? 

Thank you
Shaked

**Comment by Shaked** [comment]
I was thinking about something like:

`Messenger.php`
```
     /**
+     * @param $recipient
+     * @param NotificationType $notificationType
+     */
+    public function setTypingStatus($recipient, $typingIndicator) {
+        $options = RequestOptionsFactory::createForTyping($recipient, $typingIndicator);
+        $this->client->send('POST', '/me/messages', null, [], [], $options);
+    }
+
```

and then
```
+class RequestOptionsFactory {
+
+    /**
+     * @param $recipientOrPhone
+     * @param $typingIndicator
+     * @return mixed
+     */
+    public static function createForTyping($recipientOrPhone, $typingIndicator) {
+        $options = [];
+        $data = [
+            'recipient'     => self::createRecipientField($recipientOrPhone),
+            'sender_action' => $typingIndicator,
+        ];
+        $options[RequestOptions::JSON] = $data;
+
+        return $options;
+    }
+
```

And of course... 
```
+<?php
+
+namespace Tgallice\FBMessenger;
+
+interface TypingIndicator {
+
+    /**
+     * Mark last message as read
+     */
+    const MARK_SEEN = 'mark_seen';
+
+    /**
+     * Turn typing indicators on
+     */
+    const TYPING_ON = 'typing_on';
+
+    /**
+     * Turn typing indicators off
+     */
+    const TYPING_OFF = 'typing_off';
+
+}
```

Feel free to comment and if it's ok I will send a pull request. 

Shaked

**Comment by tgallice** [comment]
Hello @Shaked ! You absolutely right, this feature is missing and need to be added :) I like your idea ! If you have already implement something feel free to open a PR or I will handle it. 

Thanks

**Comment by Shaked** [comment]
@tgallice - Actually I have. I will send a pull request ASAP.

Thank you!

**Comment by tgallice** [comment]
Thank @Shaked ! I have merge your PR, we can close this one.
