### ISSUE TITLE
Basic use fails: Call to undefined method Tgallice\FBMessenger\Messenger::create()

### ISSUE THREAD

**Issue by stevenmc** [tgallice/fb-messenger-sdk#55]
When I attempt to use this library I get a failure at step 1. 
I'm correctly using autoloading and composer, and have installed this library according to instructions. 
I am using the correct libraries at the beginning of my class, but when I try to make a basic request I get:

`use Tgallice\FBMessenger\Client;`
`use Tgallice\FBMessenger\Messenger;`

Then I do (where FB_PAGE_TOKEN is a valid token):

`$messenger = Messenger::create(FB_PAGE_TOKEN);`

And I get:

"Fatal error: Call to undefined method Tgallice\FBMessenger\Messenger::create()".

Is the documentation correct?

**Comment by stevenmc** [comment]
Seems to only be usable when I install via: 

`composer require tgallice/fb-messenger-sdk:1.0.x-dev`

Is this correct?

**Comment by AlphawolfWMP** [comment]
Have you tried

```
$client = new Client('<PAGE_TOKEN>');
$messenger = new Messenger($client);
```

instead?

**Comment by stevenmc** [comment]
Yes, same result.

**Comment by AlphawolfWMP** [comment]
What PHP version are you running?

**Comment by stevenmc** [comment]
PHP 5.6.30

**Comment by stevenmc** [comment]
Like I say, it works with:

`composer require tgallice/fb-messenger-sdk:1.0.x-dev`

Anyway, on another note, the ID you get from messenger isn't the real Facebook ID of the user, it's page specific. Facebook provides a mechanism to get the real Facebook ID, as documented here:
https://developers.facebook.com/docs/messenger-platform/connecting-accounts

Do you have any plans to add a `getFacebookId()` method to your library?

**Comment by stevenmc** [comment]
I'm also getting:

`Fatal error: Class 'Tgallice\FBMessenger\Model\ThreadSetting\WebUrl' not found`

When setting a persistent menu. Is that because I'm using this?

`composer require tgallice/fb-messenger-sdk:1.0.x-dev`

**Comment by AlphawolfWMP** [comment]
> The ThreadSetting.php model appears to be mostly empty.

Try `Tgallice\FBMessenger\Model\Button\WebUrl` instead of `Tgallice\FBMessenger\Model\ThreadSetting\WebUrl`

Maybe you should also have a look at the example repo: https://github.com/tgallice/fb-bot-example

**Comment by stevenmc** [comment]
Thank you for this advice, yes, `Tgallice\FBMessenger\Model\Button\WebUrl` is the correct path, thank you.
I'll review the `fb-bot-example` too. That's great, thanks for the pointers.
