### ISSUE TITLE
Send API Reference "messaging_type"

### ISSUE THREAD

**Issue by Shucach** [tgallice/fb-messenger-sdk#58]
Will be updated? Need to add messaging_type. Or how add messaging_type.?
https://developers.facebook.com/docs/messenger-platform/reference/send-api/?locale=en_US

**Comment by Shucach** [comment]
Thanks.

**Comment by jonkofee** [comment]
@Shucach no, this pull request is not merged. Reopen please

**Comment by jonkofee** [comment]
When merge, this issues automatically closes
